repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml           # Проверяет синтаксис YAML файлов
      - id: end-of-file-fixer    # Убеждается, что файлы заканчиваются пустой строкой
      - id: trailing-whitespace  # Удаляет лишние пробелы в конце строк
        exclude: '\.md$'
      - id: check-added-large-files # Предотвращает коммит больших файлов (например, .env или БД)
      - id: detect-private-key   # Проверяет, что не коммитятся приватные ключи

  - repo: local
    hooks:
      - id: pip-audit
        name: pip-audit
        entry: pip-audit -r requirements.txt
        language: system
        files: requirements.txt
        pass_filenames: false